package com.ripenapps.greenhouse.utills

object Constants {
    const val TOKEN: String = "token"
    const val PROFILE_DATA = "user_details"
    const val FRUITS = "65c3c6f56aa05c59c20219fa"
    const val DATES = "65c3c6536aa05c59c20219f2"
    const val VEGETABLES = "65c3c6a06aa05c59c20219f6"
    const val VEGETABLESMYBID = "Vegetables"
    const val DATESMYBID = "Dates"
    const val FRUITSMYBID = "Fruits"
    const val WON_STATUS = "won"
    const val LOST_STATUS = "lost"
    const val CONSTANTS = "Confirmed"
    const val DELIVERED = "Delivered"
    const val CANCELLED = "Cancelled"
    const val RETURNED = "Returned"
    const val RECEIVED = "Received"
    const val ORDER_ID = "orderId"
    const val SELLER_ID = "sellerId"
    const val PACKED = "Packed"
    const val CONFIRMED = "Confirmed"
    const val PAGING = "paging"
    const val PRODUCT_ID = "productId"
    const val SUB_CATEGORY_NAME = "sub_category_name"
    const val CATEGORY_NAME = "category_name"
    const val CATEGORY_ID = "categoryId"
    const val ADMIN_ID = "65cbedee19ae0d44843c7ae6" //65cbedee19ae0d44843c7ae6
    const val DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    const val CC = "+966"
    var SELECTED_LANGUAGE = "en"
    var GOOGLE_MAP_KEY = "AIzaSyCvDTbsA0STAigxbWU2BJRfQpEt11ah0a4"
    const val ROOM_DATA = "room_data"
    const val TICKET_ID = "ticket_id"
}